# Generated by Django 5.2.3 on 2025-06-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'SuperAdmin'), ('schooladmin', 'SchoolAdmin'), ('departmenthead', 'DepartmentHead'), ('staff', 'Staff'), ('student', 'Student')], max_length=20),
        ),
    ]
